import java.util.Scanner;
 public class NumberGame{

  public static void main(String []args){
   Scanner sc=new Scanner(System.in);
   System.out.println("Welcome to the Number Guessing Game!");
   System.out.println("Number is generated by computer between 1 and 100");
   System.out.println("Enter your guess number between 1 and 100");
   System.out.println("LETS START THE GAME !!!");
   
   int attempts=5;
   int score=0;
   System.out.println("How many rounds do you want ?");
   int rounds =sc.nextInt();
   for(int i=0;i<rounds;i++){
    int number=(int)(Math.random()*100)+1;
    for(int j=0;j<attempts;j++){
      System.out.println("Enter your guess");
     int guess=sc.nextInt();
      if(guess==number){
        System.out.println("Congratulations you guessed the number ");
        score+=1;
        break;
      }
      else if(guess<number&&j!=attempts-1){
        System.out.println("TOO LOW ! Try Again ");
    
      }
      else if(guess>number&&j!=attempts-1){
        System.out.println("TOO HIGH ! Try Again ");
        
      }
      if (j==(attempts-1)){
        if(guess>number){
          System.out.println("Too High");
          System.out.println("You have used all attempts");
          System.out.println("The number was "+number);
        }else if(guess<number){
          System.out.println("Too Low");
          System.out.println("You have used all attempts");
          System.out.println("The number was "+number);
        }
 
      }       
   }
  }
   
  System.out.println("Your score is "+score+" out of "+rounds);
   sc.close();
}


}
   